---
title: "Market Index Portafolio - Notebook Code Copilation"
author: "Edgar Sigfrido Soto Aparicio"
date: "12/18/2021"
output: html_notebook
---

# SEGUNDA PARTE. CARGAR SERIES DE LOS PAISES SELLECCIONADOS Y ANALIZARLAS

## Cargar librerias necesarias
```{r}
library(tidyverse)
library(readxl)
library(textshape)
library(broom)
library(plotly)
library(scales)
library(caTools)
library(caret)
library(cluster)
library(factoextra) #Para graficar K-Means y PCA
library(psych) 
library(stats) #Para hacer el PCA
library(naniar) #Para limpiar las bases de datos
library(fBasics)#Analisis estadistico
library(aTSA)#Raiz Unitaria
library(tseries)#Raiz Unitaria
library(PerformanceAnalytics)
library(QuantPsyc)#Pruba multivariada
library(statmod)
library(ghyp)
library(cramer)#Pra la prueba de cramer 
```



Las series no son normles ni estacionarias
```{r Datos, y forma de df}
g1<- read_excel("C:/Users/juanl/Desktop/paper/Bases de datos/Series de grupos/g1.xls")

colnames(g1)<-c("Fecha","OMX 20","STI","FTSE 100","HSI","DJI")

g1<-textshape::column_to_rownames(g1,loc=1)

```

```{r Limpieza de base}
g1<-drop_na(g1)
glimpse(g1)
#View(g1)
```


```{r Retornos}
retornos<-Return.calculate(g1,method = "log")
retornos<-drop_na(retornos)
#,method=c("Discretos" o "log"1)
```

```{r Estadistica de los retornos}
Estg1<-basicStats(retornos)
Estg1
```



```{r Prueba de raiz unitaria}
adf.test(retornos$STI)
adf.test(retornos$OMX.20)
adf.test(retornos$FTSE.100)
adf.test(retornos$HSI)
adf.test(retornos$DJI)
```
#Todas las series son estacionarias.


```{r Pruebas de normalidad wilk}
shapiro.test(retornos$OMX.20)
shapiro.test(retornos$STI)
shapiro.test(retornos$FTSE.100)
shapiro.test(retornos$HSI)
shapiro.test(retornos$DJI)
```
#Ninguna de las series es normal


```{r Prueba de normalidad Kormogorov}
m<-mean(retornos$OMX.20)
sd<-sd(retornos$OMX.20)
len<-length(retornos$OMX.20)

basenormal<-rnorm(len,m,sd)#normal con los parametros de nuestras series

ks.test(retornos$OMX.20,basenormal)

plot(density(retornos$OMX.20),
     col="blue",ylim=c(0,60), main="Distribuciones contra normal")+ 
     legend("topleft",c("OMX","STI"))+
    lines(density(retornos$STI),
        col="green")+
    lines(density(retornos$FTSE.100),
        col="orange")+
    lines(density(retornos$HSI),
        col="black")+
    lines(density(retornos$DJI),
        col="grey")+
  lines(density(basenormal),
        col="red")

ks.test(retornos$STI,basenormal)
ks.test(retornos$FTSE.100,basenormal)
ks.test(retornos$HSI,basenormal)
ks.test(retornos$DJI,basenormal)
```


```{r Shapiro Francia}
sfTest(retornos$OMX.20)
sfTest(retornos$STI)
sfTest(retornos$FTSE.100)
sfTest(retornos$HSI)
sfTest(retornos$DJI)
```

```{r Pruba de normalidad multivariada}
mult.norm(retornos)$mult.test
```

```{r Construccion de NIG univariada}

      NIG<-nigFit(retornos$STI)#da los parametros para la NIG

   a<-NIG@fit[["par"]]#localizar parametros
   
   a<-data.frame(t(a))
   
   r = rnig(len,
            alpha = a$alpha , 
            beta = a$beta, 
            delta = a$delta ,
            mu= a$mu)
   
   hist(r, 
        n = 25, 
        probability = TRUE, 
        border = "white", 
        col = "steelblue")#Porque probability
  
 ks.test(retornos$DJI,r)
 #Comparacion con la NIG
```

```{r Construccion  NIG multivariada}
multNIG<-fit.NIGmv(data=retornos,silent=FALSE)
Mom1NIGm<-multNIG@expected.value
Mom2NIGm<-multNIG@variance

Mom1NIGm
Mom2NIGm
summary(multNIG)

#COnstruccion de la funcion NIG con nuestros  parametros de la funcion multivariada
n<-100000
Mnig <- rghyp(n,multNIG)

plot(density(Mnig))

ks.test(retornos$HSI,Mnig)

```











