---
title: "Untitled"
author: "Juan Luis Gonzalez A01651676"
date: "25/10/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Librerias
```{r setup, include=FALSE}
library(readxl)#Leer excel
library(factoextra)#funcion kmeans
library(textshape)#editar las columnas}
library(tidyverse)#Permite hacer el modelo para la grafica de Elbow Method
library(cluster)

```
#Carga de base de datos
```{r}
df1 <- data.frame(read_excel("C:/Users/juanl/Desktop/paper/Criterios - Unificado.xlsx"))#Carga los datos
df1<-textshape::column_to_rownames(df1,loc=1)
df2<-df1[(rownames(df1)!="China"),]
df3<-df2[(rownames(df2)!="United States"),]
```

#Dimencionado de datos y seed para kmeans
```{r}
scaledD <- scale(df3)
#View(scaledD)
set.seed(123)
```

#Elbow Method
```{r}
fviz_nbclust(df3, kmeans, method = "wss")
```

#Gap Method
```{r}
#calculate gap statistic based on number of clusters
gap_stat <- clusGap(scaledD,FUN = kmeans,nstart = 25,K.max = 30,B = 50)

#plot number of clusters vs. gap statistic
fviz_gap_stat(gap_stat)
```

#Agrupacion por clusters
```{r}
km<- kmeans(df3, centers = 4, iter.max =1000, nstart =1)
fviz_cluster(km, data = df3)#Grafica K means
df3<-df3%>%
  mutate(cluster=km$cluster)
View(df3)

Cluster1<-df3%>%
  filter(cluster=="1")

View(Cluster1)
```


